name: Convert Excel to CSV Stramien (Minimal)

on:
  workflow_dispatch:
    inputs:
      sheet:
        description: 'Optionele sheetnaam'
        required: false
        default: ''
      cutoff:
        description: 'Fuzzy cutoff (0..1)'
        required: false
        default: '0.86'
  push:
    paths:
      - 'input/**'
      - 'template/**'
      - 'excel_to_stramien.py'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run conversion
        run: |
          SHEET="${{ github.event.inputs.sheet }}"
          CUTOFF="${{ github.event.inputs.cutoff }}"
          if [ -z "$SHEET" ]; then
            python excel_to_stramien.py --input input --template template/import-organizations.csv --output output --cutoff ${CUTOFF}
          else
            python excel_to_stramien.py --input input --template template/import-organizations.csv --output output --sheet "$SHEET" --cutoff ${CUTOFF}
          fi
      - name: Upload CSVs
        uses: actions/upload-artifact@v4
        with:
          name: converted-csv
          path: output/*.csv
